name: PulseML MLOps CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r api/requirements.txt
          pip install pytest

      - name: Train dummy model for testing
        run: python model/train.py

      - name: Run Tests
        env:
          PYTHONPATH: .
        run: pytest tests/ -v

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Hugging Face CLI
        run: pip install huggingface_hub

      - name: Deploy API to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |-
          huggingface-cli upload gerakp/pulseml-api ./api . --repo-type space --token $HF_TOKEN

      - name: Deploy Dashboard to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |-
          huggingface-cli upload gerakp/pulseml-dashboard ./dashboard . --repo-type space --token $HF_TOKEN
